### ISSUE TITLE
JavaScriptのconsole.logは標準出力と言っていいのか？

### ISSUE THREAD

**Issue by OST-Kawachi** [OST-Kawachi/NewcomerTraining#7]
微妙

**Comment by kazuhikoh** [comment]
全く別物なので、これはだめでしょ！
「標準出力=アプリからの一番基本的な出力方法」 みたいな誤った解釈をさせる危険が...

「標準出力」は、カーネルがプロセスごとに用意する出力先の名前。
端末やファイルに紐付けられるから、端末に文字をだしたり、ファイルに書き込んだりできる。

「console.log」は、あくまでブラウザの機能。
ブラウザのjs実行エンジンに用意されているconsoleオブジェクトをつかうと、ブラウザにlogがだせるというだけ。
ブラウザで実行させたjsから標準出力に出力する方法は用意されてない(はず)。

**Comment by OST-Kawachi** [comment]
なるほど了解  
じゃあ標準出力欄にconsole.logを書くのは無しの方向で  
どこに書くかは別Issueで #93
